In [16]:
import pandas as pd
import numpy as np
import seaborn
import warnings
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

In [17]:
df_loan = pd.read_csv("./datasets/train_ctrUa4K.csv")

In [18]:
df_loan.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [19]:
nulls = pd.DataFrame({
    'Missing_Count': df_loan.isnull().sum(),
    'Missing_Percent': round(df_loan.isnull().mean() * 100, 2)
})

nulls = nulls[nulls['Missing_Count'] > 0].sort_values('Missing_Count', ascending=False)
print(nulls)

                  Missing_Count  Missing_Percent
Credit_History               50             8.14
Self_Employed                32             5.21
LoanAmount                   22             3.58
Dependents                   15             2.44
Loan_Amount_Term             14             2.28
Gender                       13             2.12
Married                       3             0.49

In [30]:
df_loan.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status
count,614.000000,614.000000,592.000000,600.00000,564.000000,614.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199,0.687296
std,6109.041673,2926.248369,85.587325,65.12041,0.364878,0.463973
min,150.000000,0.000000,9.000000,12.00000,0.000000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000,0.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000,1.000000

In [ ]:
df_loan['Loan_Status'].value_counts(dropna=False).reset_index()

  Loan_Status  count
0           Y    422
1           N    192

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_loan['Loan_Status'] = le.fit_transform(df_loan['Loan_Status'])
print(dict(zip(le.classes_, le.transform(le.classes_))))

{'N': np.int64(0), 'Y': np.int64(1)}

In [29]:
df_gender = df_loan.groupby(by='Gender', as_index=False, dropna=False).agg({
    'Loan_ID': 'count', 'Loan_Status': 'mean', 'ApplicantIncome': 'mean', 'CoapplicantIncome': 'mean', 'LoanAmount': 'mean', 'Loan_Amount_Term': 'mean'
})
df_gender.head()

,Gender,Loan_ID,Loan_Status,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term
0,Female,112,0.669643,4643.473214,1108.008929,126.697248,352.293578
1,Male,489,0.693252,5446.460123,1742.932352,149.265957,339.665272
2,NaN,13,0.615385,10333.538462,1465.692308,208.538462,341.538462

In [22]:
df_loan['Education'].value_counts(dropna=False).reset_index()

      Education  count
0      Graduate    480
1  Not Graduate    134

In [23]:
df_loan['Self_Employed'].value_counts(dropna=False).reset_index()

  Self_Employed  count
0            No    500
1           Yes     82
2           NaN     32

In [24]:
df_loan['Property_Area'].value_counts(dropna=False).reset_index()

  Property_Area  count
0     Semiurban    233
1         Urban    202
2         Rural    179

In [24]:
df_train.groupby(by='Self_Employed').agg({'status': 'mean'})

                 status
Self_Employed
No             0.686000
Yes            0.682927

In [25]:
df_train.groupby(by='Loan_Status').agg({'ApplicantIncome': 'mean'})

             ApplicantIncome
Loan_Status
N                5446.078125
Y                5384.068720

In [31]:
df_train.groupby(by=['Loan_Status', 'Dependents']).agg({'CoapplicantIncome': 'mean'})

                        CoapplicantIncome
Loan_Status Dependents
N           0                 1596.943925
            1                 1832.972222
            2                 1599.040000
            3+                4290.111111
Y           0                 1635.723193
            1                 1204.378788
            2                 1716.260526
            3+                 788.424242

In [32]:
df_train.groupby(by='Loan_Status').agg({'Credit_History': 'mean'})

             Credit_History
Loan_Status
N                  0.541899
Y                  0.981818